### ISSUE TITLE
Use pretrained model

### ISSUE THREAD

**Issue by MarkMobini** [mingcv/YTMT-Strategy#9]
Hi.
Thanks for sharing your work.
How can i use the pre-trained model on an image for reflection removal?
I searched the code and did not find it. 
By the way in utils.py ==> :

skimage.measure.compare_psnr to skimage.metrics.peak_signal_noise_ratio. 

thanks.

**Comment by mingcv** [comment]
1. We have described the testing procedure in [README.md](https://github.com/mingcv/YTMT-Strategy#testing) and you can uncomment [Line 24](https://github.com/mingcv/YTMT-Strategy/blob/d18d19ce930a355e6fd6e71b302d5d3fd75b7fb5/test_sirs.py#L24) and [Line 71](https://github.com/mingcv/YTMT-Strategy/blob/d18d19ce930a355e6fd6e71b302d5d3fd75b7fb5/test_sirs.py#L71) and pass the path of the testing dir to datasets.RealDataset, in order to process custom images. Moreover, we will release a notebook demo with minimal dependencies before long. 
2. Thanks, I will write a try-catch block for handling the version-related issues about the skimage package.
